
typedef union 
{int ival;
 long lval;
 reals dval;
 char *sval;
 selm seval;
 xelm xval;
} YYSTYPE;
extern YYSTYPE yylval;
# define DECL 257
# define EXP 258
# define STRU 259
# define FUNCDECL 260
# define COMMDECL 261
# define COMMTYPE 262
# define NODEPARMS 263
# define PR1 264
# define LSBRK 265
# define LNUMBER 266
# define INUMBER 267
# define DNUMBER 268
# define IDENT 269
# define FIDENT 270
# define VIDENT 271
# define CBIN 272
# define CPILE 273
# define CHEAP 274
# define SQCHR 275
# define DQSTR 276
# define MULEQ 277
# define DIVEQ 278
# define MODEQ 279
# define PLUEQ 280
# define MINEQ 281
# define ANDEQ 282
# define XOREQ 283
# define OREQ 284
# define LSEQ 285
# define RSEQ 286
# define DOTDOT 287
# define DOTSEP 288
# define DOTDOTSEP 289
# define DOTDOTID 290
# define OROR 291
# define ANDAND 292
# define EQ 293
# define NE 294
# define LE 295
# define GE 296
# define LS 297
# define RS 298
# define COPBRK 299
# define PLUPLU 300
# define MINMIN 301
# define UMINUS 302
# define ATPIP 303
# define ATQST 304
# define ATEXC 305
# define STARSTAR 306
# define DOLQUEST 307
# define DOLDOL 308
# define DOLSEL 309
# define DOLEXC 310
# define DOLEXCEXC 311
# define LSTSTAR 312
# define LSTOPR 313
# define LABEL 314
# define LABELARY 315
# define NET 316
# define NETARGS 317
# define NODE 318
# define CDO 319
# define CFOR 320
# define CWHILE 321
# define CIF 322
# define CELSE 323
# define CBREAK 324
# define CIDENT 325
